## COLORSCHEME: tokyo-night

# Backgrounds
set -g @tokyo_bg_dim '#1a1b26'
set -g @tokyo_bg0 '#1f2335'
set -g @tokyo_bg1 '#2a2e44'
set -g @tokyo_bg2 '#32344a'
set -g @tokyo_bg3 '#414868'
set -g @tokyo_bg4 '#51576d'
set -g @tokyo_bg_visual '#2d3242'
set -g @tokyo_bg_red '#f7768e'
set -g @tokyo_bg_green '#9ece6a'
set -g @tokyo_bg_blue '#7aa2f7'
set -g @tokyo_bg_yellow '#e0af68'

# Foregrounds
set -g @tokyo_fg '#c0caf5'
set -g @tokyo_red '#f7768e'
set -g @tokyo_orange '#ff9e64'
set -g @tokyo_yellow '#e0af68'
set -g @tokyo_green '#9ece6a'
set -g @tokyo_aqua '#2ac3de'
set -g @tokyo_blue '#7aa2f7'
set -g @tokyo_purple '#bb9af7'
set -g @tokyo_grey0 '#565f89'
set -g @tokyo_grey1 '#6b7394'
set -g @tokyo_grey2 '#7e88a2'
set -g @tokyo_statusline1 '#9ece6a'
set -g @tokyo_statusline2 '#c0caf5'
set -g @tokyo_statusline3 '#f7768e'

# Status bar
set-option -g status "on"
set -g status-interval 2
set-option -g status-fg '#c0caf5'
set-option -g status-bg '#1f2335'
set-option -g mode-style fg='#{@tokyo_purple}',bg='#{@tokyo_bg_red}'
set-option -g status-style fg='#{@tokyo_fg}',bg='#{@tokyo_bg_dim}',default

# Windows
set-window-option -g window-status-style fg='#{@tokyo_bg4}',bg='#{@tokyo_bg0}'
set-window-option -g window-status-activity-style 'bg=#{@tokyo_bg1},fg=#{@tokyo_bg3}'
set-window-option -g window-status-current-style fg='#{@tokyo_fg}',bg='#{@tokyo_bg_green}'

# Panes
set-option -g pane-border-style fg='#{@tokyo_bg1}'
set-option -g pane-active-border-style 'fg=#{@tokyo_blue}'
set-option -g display-panes-active-colour '#7aa2f7'
set-option -g display-panes-colour '#ff9e64'

# Command messages
set-option -g message-style fg='#{@tokyo_statusline3}',bg='#{@tokyo_bg_dim}'
set-option -g message-command-style 'fg=#{@tokyo_bg3},bg=#{@tokyo_bg1}'

# Clock
set-window-option -g clock-mode-colour '#7aa2f7'

# Bell
set-window-option -g window-status-bell-style fg='#{@tokyo_bg0}',bg='#{@tokyo_statusline3}'

# Formatting
set-option -g status-left-style none
set -g status-left-length 60
set -g status-left '#[fg=#{@tokyo_bg_dim},bg=#{@tokyo_green},bold] #S #[fg=#{@tokyo_green},bg=#{@tokyo_bg2},nobold]#[fg=#{@tokyo_green},bg=#{@tokyo_bg2},bold] #(whoami) #[fg=#{@tokyo_bg2},bg=#{@tokyo_bg0},nobold]'

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right '#[fg=#{@tokyo_bg2}]#[fg=#{@tokyo_fg},bg=#{@tokyo_bg2}] #[fg=#{@tokyo_fg},bg=#{@tokyo_bg2}]%Y-%m-%d  %H:%M #[fg=#{@tokyo_aqua},bg=#{@tokyo_bg2},bold]#[fg=#{@tokyo_bg_dim},bg=#{@tokyo_aqua},bold] #h '

set -g window-status-separator '#[fg=#{@tokyo_grey2},bg=#{@tokyo_bg0}] '
set -g window-status-format "#[fg=#{@tokyo_grey0},bg=#{@tokyo_bg0}] #I  #[fg=#{@tokyo_grey0},bg=#{@tokyo_bg0}]#W "
set -g window-status-current-format "#[fg=#{@tokyo_bg0},bg=#{@tokyo_bg_green}]#[fg=#{@tokyo_fg},bg=#{@tokyo_bg_green}] #I  #[fg=#{@tokyo_fg},bg=#{@tokyo_bg_green},bold]#W #[fg=#{@tokyo_bg_green},bg=#{@tokyo_bg0},nobold]"
