device {
  name = mx-mchncl-keyboard
  kb_layout = us,br
  kb_options = ctrl:nocaps, altwin:swap_alt_win, grp:alt_shift_toggle # ,grp:alts_toggle
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = br
  kb_options = ctrl:nocaps,altwin:swap_alt_win
  resolve_binds_by_sym = 1
}
