
unbind C-b
set -g prefix C-s

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
set -s escape-time 0

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# Set focus-events on (important for Neovim autoread)
set -g focus-events on

# important - 24 bit color support
set -g default-terminal "tmux-256color"
set -g terminal-overrides ',*:Tc,alacritty:RGB'

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

set-option -s escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjk
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended

# set -g @plugin 'egel/tmux-gruvbox'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Initial theme load
run-shell "~/.local/bin/omarchy-tmux-theme.sh"

# Reload theme on focus
set-hook -g client-focus-in 'run-shell "~/.local/bin/omarchy-tmux-theme.sh"'
